
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameFrameX.Config
{ 
    public enum GiftUIType
    {
        /// <summary>
        /// Normal UI
        /// </summary>
        Normal = 0,
        /// <summary>
        /// Special UI
        /// </summary>
        Style_1 = 1,
    }

} 

