
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameFrameX.Config
{ 
    public enum GiftFilterType
    {
        /// <summary>
        /// None, get all
        /// </summary>
        None = 0,
        /// <summary>
        /// Randomly get N items
        /// </summary>
        Random = 1,
        /// <summary>
        /// Custom select N items
        /// </summary>
        Custom = 2,
    }

} 

