
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameFrameX.Config
{ 
    public enum GiftModelType
    {
        /// <summary>
        /// Not previewable
        /// </summary>
        Non = 0,
        /// <summary>
        /// Single preview
        /// </summary>
        Single = 1,
        /// <summary>
        /// Full set preview
        /// </summary>
        Complete = 2,
        /// <summary>
        /// Separate preview
        /// </summary>
        Enumeration = 3,
        /// <summary>
        /// Combined preview
        /// </summary>
        Combination = 4,
    }

} 

