
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameFrameX.Config
{ 
    public enum ItemLevelColor
    {
        /// <summary>
        /// Blue
        /// </summary>
        B = 0,
        /// <summary>
        /// Purple
        /// </summary>
        A = 1,
        /// <summary>
        /// Orange
        /// </summary>
        S = 2,
        /// <summary>
        /// Red
        /// </summary>
        SR = 3,
        /// <summary>
        /// Gold
        /// </summary>
        SSR = 4,
    }

} 

