
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameFrameX.Config
{ 
    public enum ItemCanUse
    {
        /// <summary>
        /// Cannot use
        /// </summary>
        CanNot = 0,
        /// <summary>
        /// Can only use one at a time
        /// </summary>
        UseOne = 1,
        /// <summary>
        /// Can use all at once
        /// </summary>
        UseTotal = 2,
    }

} 

