
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameFrameX.Config
{ 
    public enum ItemType
    {
        /// <summary>
        /// Item
        /// </summary>
        Item = 0,
        /// <summary>
        /// Consumable
        /// </summary>
        Expendable = 1,
        /// <summary>
        /// Equipment
        /// </summary>
        Equip = 2,
        /// <summary>
        /// Fragment
        /// </summary>
        Fragment = 3,
        /// <summary>
        /// Material
        /// </summary>
        Material = 4,
        /// <summary>
        /// Quest
        /// </summary>
        Task = 5,
    }

} 

