
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameFrameX.Config
{ 
    public enum ItemSubType
    {
        /// <summary>
        /// None
        /// </summary>
        NONE = 0,
        /// <summary>
        /// Weapon
        /// </summary>
        WEAPON = 1,
        /// <summary>
        /// Chest
        /// </summary>
        CHEST = 2,
        /// <summary>
        /// Belt
        /// </summary>
        BELT = 3,
        /// <summary>
        /// Boots
        /// </summary>
        BOOT = 4,
        /// <summary>
        /// Ring
        /// </summary>
        RING = 5,
    }

} 

