
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameFrameX.Config
{ 
    public enum ItemUseLimiteType
    {
        /// <summary>
        /// No limit
        /// </summary>
        NOLIMITE = 0,
        /// <summary>
        /// Daily limit
        /// </summary>
        DAYLIMITE = 1,
        /// <summary>
        /// VIP limit
        /// </summary>
        VIPLIMITE = 2,
        /// <summary>
        /// Weekly limit
        /// </summary>
        WEEK6LIMITE = 3,
    }

} 

