
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameFrameX.Config
{ 
    public enum ItemEPrompt
    {
        /// <summary>
        /// No
        /// </summary>
        NONE = 0,
        /// <summary>
        /// New equipment
        /// </summary>
        NEW_EQUIP = 1,
        /// <summary>
        /// Red dot
        /// </summary>
        RED_POINT = 2,
    }

} 

